# Generated by Django 4.2.16 on 2024-11-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionaccount',
            name='name',
            field=models.CharField(default='Default', max_length=255),
            preserve_default=False,
        ),
    ]
